[FE] REFACTOR: CabinetInfoArea 컨테이너, Presentational 파트 구분 및 리팩토링 #1037
innovationacademy-kr/42cabi pull request #1117
Opened 2023-05-23 10:36 UTC by oyhoyhk

## 해당 사항 (중복 선택)

- [ ] FEAT : 새로운 기능 추가 및 개선
- [ ] FIX : 기존 기능 수정 및 정상 동작을 위한 간단한 추가, 수정사항
- [ ] BUG : 버그 수정
- [x] REFACTOR : 결과의 변경 없이 코드의 구조를 재조정
- [ ] TEST : 테스트 코드 추가
- [ ] DOCS : 코드가 아닌 문서를 수정한 경우
- [ ] REMOVE : 파일을 삭제하는 작업만 수행
- [ ] RENAME : 파일 또는 폴더명을 수정하거나 위치(경로)를 변경
- [ ] ETC : 이외에 다른 경우 - 어떠한 사항인지 작성해주세요.

## 설명
>아래 링크에 이슈번호를 적어주세요. 예) .../42cabi/issues/738

https://github.com/innovationacademy-kr/42cabi/issues/1037

저희가 설계 단계에서 채택한 Container / Presentational 컴포넌트 방식에 맞지 않는 

CabinetInfoArea, AdminCabinetInfoArea, CabinetInfoArea.container 컴포넌트에서

container에는 로직만, presentational 파트에는 스타일만을 가지도록 코드를 수정하고

state들을 하나의 객체로 관리하여 코드의 양과 가독성을 높일 수 있도록 리팩토링 하였습니다

2023-05-23 11:07 UTC, YESHYUNGSEOK commented
제가 보기에는 깔끔하게 잘 정리해 주신 것 같습니다ㅎㅎ 고생하셨습니다!!

2023-05-23 11:08 UTC, YESHYUNGSEOK approved these changes
제가 보기에는 깔끔하게 잘 정리해 주신 것 같습니다ㅎㅎ 고생하셨습니다!!

2023-05-24 02:42 UTC, 42inshin requested changes

2023-05-24 02:42 UTC, 42inshin commented on frontend/src/components/CabinetInfoArea/CabinetInfoArea.container.tsx
> +import { useState } from "react";
import 순서 저희 따로 컨벤션에 적어두진 않았으나, 라이브러리 훅들은 올리고 컴포넌트는 아래로 가는 식으로 적자고 작업할 당시에 얘기했던거 같은데, 이번 기회에 정하는게 어떨까요!?

2023-05-24 02:48 UTC, 42inshin commented
내용이 내용인만큼 정리하기 쉽지 않았을텐데 container로 잘 분리해놓으셨네요. 기능 부분 빼는 작업 어려웠을거라 생각이듭니다. 
다만, container 파일로 기능 빼면서 코드 읽기가 더 어려워진 느낌이 있습니다.
지금 하는 작업이 코드 리팩토링인 만큼 가독성을 높일 수 있도록 추가 컨벤션 기준을 정해서 정리해보는 것이 좋을 것 같다는 생각이 듭니다ㅎㅎ

2023-05-25 04:47 UTC, seong-hui approved these changes
코드 정리가 잘 되었다고 생각합니다. 고생하셨습니다!

2023-06-19 09:53 UTC, 42inshin commented
리팩토링 작업을 통해서 해당 부분 변경되었으므로 PR close 하도록 하겠습니다! (해당 내용은 형노님께서 수정해서 올려놓으셨습니다)

2023-06-19 09:53 UTC, closed without merging