Fe/dev/ Cabinetlist, Userinfoarea 리팩토링/#1137
innovationacademy-kr/42cabi pull request #1149
Opened 2023-05-31 04:37 UTC by YESHYUNGSEOK

## 해당 사항 (중복 선택)

- [ ] FEAT : 새로운 기능 추가 및 개선
- [ ] FIX : 기존 기능 수정 및 정상 동작을 위한 간단한 추가, 수정사항
- [ ] BUG : 버그 수정
- [x] REFACTOR : 결과의 변경 없이 코드의 구조를 재조정
- [ ] TEST : 테스트 코드 추가
- [ ] DOCS : 코드가 아닌 문서를 수정한 경우
- [ ] REMOVE : 파일을 삭제하는 작업만 수행
- [ ] RENAME : 파일 또는 폴더명을 수정하거나 위치(경로)를 변경
- [ ] ETC : 이외에 다른 경우 - 어떠한 사항인지 작성해주세요.

## 설명

CabinetList와 UserInfoArea 디렉토리의 리팩토링 작업을 진행하였습니다.

https://github.com/innovationacademy-kr/42cabi/issues/

2023-05-31 05:05 UTC, 42inshin commented
제목 컨벤션 맞춰주세요~~!

2023-05-31 05:18 UTC, YESHYUNGSEOK commented
> 제목 컨벤션 맞춰주세요~~!

수정했습니당ㅎㅎ

2023-05-31 06:36 UTC, seong-hui approved these changes
확인했습니당

2023-05-31 07:19 UTC, 42inshin requested changes
utils.ts 파일을 utils/utils.ts에 넣어뒀었는데, 밖으로 나와있어서 files changed에 잡혀있네요 이부분만 수정하시면 변경하신것 문제 없을 것 같습니다! 👍

2023-06-01 11:09 UTC, 42inshin approved these changes
고생하셨습니다!

2023-06-01 11:10 UTC, merged