[FE] FEAT: 메인 우측 구역(사물함 상세 정보) 디자인 구현 #607
innovationacademy-kr/42cabi pull request #613
Opened 2022-12-20 17:22 UTC by Oris482

## 해당 사항 (중복 선택)

- [x] FEAT : 새로운 기능 추가
- [ ] FIX : 버그 수정
- [ ] REFACTOR : 결과의 변경 없이 코드의 구조를 재조정
- [ ] TEST : 테스트 코드 추가
- [ ] ETC : 이외에 다른 경우 - 어떠한 사항인지 작성해주세요.

## 설명
### Issue
- #607 

### 상세 정보
<img width="331" alt="image" src="https://user-images.githubusercontent.com/60038526/208727000-50ee5dd4-02c0-4b45-911d-86c217915ff8.png">

버튼은 만들어주신 걸로 대체될 예정입니다.

구현된 디자인
- 사물함 상태에 따른 사각형 배경 색 변경(내 사물함, 대여가능, 이용중, 연체, 고장)
- 사물함 타입에 따른 아이콘 변경(개인, 공유, 동아리)
- 사물함 이용 중인 명단 출력

### 추가 필요
버튼 하단 부분에 적힐 메시지 구현
- 연체 일수 알림
- 고장 안내(사유가 노출 될 필요 여부)

2022-12-21 07:02 UTC, 42inshin requested changes
각각에 코멘트 달았습니다! 확인 부탁드릴게요!

2022-12-21 07:02 UTC, 42inshin commented on frontend_v4/src/containers/CabinetInfoArea.tsx
> +  height: 700px;
메인 컴포넌트 합칠 때 height: 100%로 바꿔야할것 같습니다

2022-12-21 07:19 UTC, Oris482 commented on frontend_v4/src/containers/CabinetInfoArea.tsx
> +      <TextStyled fontSize="16px" fontColor="black">
18px 사이즈도 있던데 이건 어떻게 사용하시나요?

2022-12-21 07:28 UTC, 42inshin commented on frontend_v4/src/containers/CabinetInfoArea.tsx
> +        <TextStyled fontSize="18px" fontColor="#7b7b7b ">
> #7b7b7b 색상도 index.css 에중(--gray-color)로 추가해 드리겠습니다.

✅ dev에 --gray-color 추가 완료했습니다

2022-12-21 07:30 UTC, 42inshin commented on frontend_v4/src/containers/CabinetInfoArea.tsx
> +      <TextStyled fontSize="16px" fontColor="black">
0.125마다 2px입니다. 18px의 경우 1.125rem 으로 쓰시면 됩니다

2022-12-21 14:29 UTC, 42inshin approved these changes
빠른 피드백 굿굿! 최곱니다

2022-12-21 23:08 UTC, oyhoyhk approved these changes
수고하셨습니다! 역시 협업 짬바가 장난아니시군요

2022-12-21 23:08 UTC, oyhoyhk commented on frontend_v4/src/containers/CabinetInfoArea.tsx
> +const CabinetInfoArea = (): JSX.Element => {
오 props 정보 미리 적어주신거 너무 좋네요

2022-12-21 23:08 UTC, oyhoyhk commented on frontend_v4/src/containers/CabinetInfoArea.tsx
> +
기능 컴포넌트를 만들 때 면 여기 있는 데이터 조작 함수 원본은 기능 컴포넌트에서 관리하게 옮겨야 할 것 같아용

참고만 해두시고 나중에 기능 컴포넌트 만들때 다시 이야기하시죠!

2022-12-22 04:01 UTC, Oris482 commented on frontend_v4/src/containers/CabinetInfoArea.tsx
> +
나눠서 짜기가 쉽지않네요🥲 강의 한 번 들으러가겠습니다..

2022-12-22 12:40 UTC, Oris482 commented
### 수정사항
<img width="300" alt="image" src="https://user-images.githubusercontent.com/60038526/209136287-b777060d-7f0e-4059-a9ea-fff2f34b05f5.png">
<img width="422" alt="image" src="https://user-images.githubusercontent.com/60038526/209136344-7520b8e1-6392-4144-b45a-eb727a930dd9.png">

container 성격에 맞게 위와 같은 객체를 props로 넘겨주면 그대로 받아서 렌더링만 하도록 수정했습니다.

2022-12-23 08:05 UTC, SeyoungCho approved these changes
확인했습니다! 감사합니다 ㅎㅎ

2022-12-23 08:05 UTC, merged