[FE] REFACTOR: Seperate MapSelect Component #747
innovationacademy-kr/42cabi pull request #749
Opened 2023-01-04 08:00 UTC by oyhoyhk

## 해당 사항 (중복 선택)

- [ ] FEAT : 새로운 기능 추가 및 개선
- [ ] BUG : 버그 수정
- [x] REFACTOR : 결과의 변경 없이 코드의 구조를 재조정
- [ ] TEST : 테스트 코드 추가
- [ ] DOCS : 코드가 아닌 문서를 수정한 경우
- [ ] REMOVE : 파일을 삭제하는 작업만 수행
- [ ] RENAME : 파일 또는 폴더명을 수정하거나 위치(경로)를 변경
- [ ] ETC : 이외에 다른 경우 - 어떠한 사항인지 작성해주세요.

## 설명
>중대한 사항이라면 상세히 적어주세요.

맵을 선택하는 컴포넌트는 element 폴더에 넣어 두었습니다.

2023-01-04 09:32 UTC, SeyoungCho approved these changes
깔끔합니다!

2023-01-05 04:18 UTC, 42inshin requested changes
파일 이름만 변경하면 문제 없을 것 같습니다. 그리고 커밋 메시지를 영어보다는 한글로 적어주시면 통일성이 더 있을 것 같아요 ㅎㅎ

2023-01-05 04:18 UTC, 42inshin commented on frontend_v4/src/components/MapSelect.tsx
> +export default MapFloorSelect;
파일 이름과 export default 이름이 다릅니다 일치 시키는게 좋을 것 같습니다:)

2023-01-05 07:37 UTC, Oris482 approved these changes
컨플릭 나는 부분이랑 인신님이 얘기해주신 부분 커밋해주시고 머지하면 될 것 같습니다!
고생하셨어요~!

2023-01-05 12:42 UTC, merged