[FE] 모바일 섹션 이동 스와이프 기능 구현 #796
innovationacademy-kr/42cabi pull request #800
Opened 2023-01-13 12:07 UTC by oyhoyhk

## 해당 사항 (중복 선택)

- [x] FEAT : 새로운 기능 추가 및 개선
- [ ] FIX : 기존 기능 수정 및 정상 동작을 위한 간단한 추가, 수정사항
- [ ] BUG : 버그 수정
- [ ] REFACTOR : 결과의 변경 없이 코드의 구조를 재조정
- [ ] TEST : 테스트 코드 추가
- [ ] DOCS : 코드가 아닌 문서를 수정한 경우
- [ ] REMOVE : 파일을 삭제하는 작업만 수행
- [ ] RENAME : 파일 또는 폴더명을 수정하거나 위치(경로)를 변경
- [ ] ETC : 이외에 다른 경우 - 어떠한 사항인지 작성해주세요.

## 설명
>아래 링크에 이슈번호를 적어주세요. 예) .../42cabi/issues/738

모바일 섹션 이동 스와이프 기능 구현

https://github.com/innovationacademy-kr/42cabi/issues/796

2023-01-13 16:20 UTC, 42inshin requested changes
코드에 코멘트 남겼습니다:) 확인부탁드릴게요!

2023-01-13 16:20 UTC, 42inshin commented on frontend/src/pages/Layout.tsx
> +  };
스와이프하는 값에 최소 값이 없어서 클릭을 하는 경우에도 moveToLeftSection나 moveToRightSection 가 동작합니다. 
이로인해 기존의 페이지네이션 기능이 왼쪽클릭시 멈추고, 오른쪽 클릭시 두번 넘어가는 등의 오작동이 일어나고 있습니다.

아래의 방식으로 swipeDistance의 최소값을 두어 그 값보다 작은 경우, return 하는 식으로 처리하면 문제 없어 보이네요!

```
  const swipeSection = (last: number) => {
    const swipeDistance = Math.round(last - touchOffset);
    if (Math.abs(swipeDistance) < 50) return;
    if (swipeDistance > 0) moveToLeftSection();
    else moveToRightSection();
  };
```

2023-01-14 04:51 UTC, oyhoyhk commented on frontend/src/pages/Layout.tsx
> +  };
그러네요 일단은 최소값 기준을 50으로 수정해보겠습니다!!

2023-01-14 10:24 UTC, Oris482 approved these changes
확인했습니다!
다만 Layout이 최상단 컴포넌트라 여기서 atom 값을 구독하는 건 비용이 꽤 많이 들 것 같습니다.
나중에 다같이 리팩토링할 때 한 번 대안을 고민해봅시당

2023-01-14 10:25 UTC, merged