[BE] FEAT: admin 로그인 실패시 리디렉션 및 로거 추가 #834
innovationacademy-kr/42cabi pull request #844
Opened 2023-01-19 11:33 UTC by Ssuamje

## 해당 사항 (중복 선택)

- [x] FEAT : 새로운 기능 추가 및 개선
- [x] FIX : 기존 기능 수정 및 정상 동작을 위한 간단한 추가, 수정사항
- [ ] BUG : 버그 수정
- [ ] REFACTOR : 결과의 변경 없이 코드의 구조를 재조정
- [ ] TEST : 테스트 코드 추가
- [ ] DOCS : 코드가 아닌 문서를 수정한 경우
- [ ] REMOVE : 파일을 삭제하는 작업만 수행
- [ ] RENAME : 파일 또는 폴더명을 수정하거나 위치(경로)를 변경
- [ ] ETC : 이외에 다른 경우 - 어떠한 사항인지 작성해주세요.

## 설명
>아래 링크에 이슈번호를 적어주세요. 예) .../42cabi/issues/738

https://github.com/innovationacademy-kr/42cabi/issues/834

어드민 로그인 실패시(잘못된 로그인 또는 로그인 하였으나 role이 권한 승인 대기상태 : 0 인 경우,
api/admin/auth/login/failure로 리디렉션 하게끔 설정하였습니다.

더해서, 로거를 추가하고 기존의 로깅 문장을 조금 다듬었습니다.

++
어드민 로그인 실패에 대한 페이지도 만들어 주시면 감사하겠습니다!
'승인 되지 않은 사용자'인 것을 인지하게끔 해주시고, 
다시 로그인 할 수 있게끔 ('api/admin/auth/login')으로 연결되는 버튼이 있으면 좋을 것 같습니다!

2023-01-19 13:16 UTC, 42inshin requested changes
api/ 가 붙는 주소는 프론트에서 백엔드 api를 요청할 때 주로 사용하고 있습니다.

리다이렉션을 프론트로 하는 경우, 프론트 주소 + "/admin/login/failure" 로 보내주셔야 합니다

2023-01-19 13:16 UTC, 42inshin commented on backend/src/admin/auth/google/google.auth.filter.ts
> +    }
제 로컬에서 테스트해봤을때 리다이렉트가 아래 주소로 갑니다 
`http://localhost/api/admin/auth/login/api/admin/auth/login/failure`

2023-01-19 13:28 UTC, Ssuamje commented on backend/src/admin/auth/google/google.auth.filter.ts
> +    }
다시 한번 체크해보고 말씀해주신대로 수정해서 커밋하겠습니다~

2023-01-20 03:09 UTC, sichoi42 approved these changes
수고하셨습니다~~ 😊

2023-01-20 04:53 UTC, eunbi9n approved these changes
고생하셨습니다!!!!!!!!!!

2023-01-20 05:33 UTC, 42inshin approved these changes
고생하셨습니다!

2023-01-20 08:08 UTC, Oris482 approved these changes
확인했습니다!

2023-01-20 08:10 UTC, merged