[FE] FEAT: 일반 유저가 개인 로그 확인하는 기능 추가 #849
innovationacademy-kr/42cabi pull request #863
Opened 2023-01-20 08:41 UTC by oyhoyhk

## 해당 사항 (중복 선택)

- [x] FEAT : 새로운 기능 추가 및 개선
- [ ] FIX : 기존 기능 수정 및 정상 동작을 위한 간단한 추가, 수정사항
- [ ] BUG : 버그 수정
- [ ] REFACTOR : 결과의 변경 없이 코드의 구조를 재조정
- [ ] TEST : 테스트 코드 추가
- [ ] DOCS : 코드가 아닌 문서를 수정한 경우
- [ ] REMOVE : 파일을 삭제하는 작업만 수행
- [ ] RENAME : 파일 또는 폴더명을 수정하거나 위치(경로)를 변경
- [ ] ETC : 이외에 다른 경우 - 어떠한 사항인지 작성해주세요.

## 설명
>아래 링크에 이슈번호를 적어주세요. 예) .../42cabi/issues/738

https://github.com/innovationacademy-kr/42cabi/issues/849

개인 로그 확인하는 컴포넌트 제작 및 api까지 붙였습니다.

백엔드쪽 api 응답 쪽에 문제가 있어 추후 api를 고치면 응답만 확인하면 될것 같습니다.

2023-01-20 11:37 UTC, 42inshin commented
로그 클릭 시 log 페이지가 나오도록 처리되었고, 이전에 있던 log모달은 admin에서 사용할 계획입니다. 
현재는 확인을 위해서 log 페이지 제목 클릭 시 log모달이 나오게 코드가 적혀있습니다.
추후 삭제될 예정입니다.

2023-01-20 14:41 UTC, 42inshin approved these changes
yooh님과 같이 화면 공유로 상의 후 코드 합쳤습니다

2023-01-20 16:27 UTC, 42inshin commented
이전에 작업한 LeftNav container 분리 작업 머지된 후 comflict 나는 부분이 있어서 수정했습니다.

2023-01-20 16:29 UTC, 42inshin commented
backend api 가 수정되면서 axios.custom에 axiosMyLentLog 기능도 기존의 param에서 query 방식으로 변경했습니다.

2023-01-23 07:41 UTC, Oris482 requested changes
Suspense 안쓰시면 이것만 빼고 커밋 푸시해주시면 감사하겠습니다!

2023-01-23 07:41 UTC, Oris482 commented on frontend/src/App.tsx
> +import React, { Suspense } from "react";
아직 안쓰는 부분인거 같은데 빼도 될까요?
나중에 사용할 때 변경점으로 나오는게 더 읽기 좋을 듯 합니다!

2023-01-23 07:41 UTC, Oris482 commented on frontend/src/pages/LogPage.tsx
> +      <LogTable data={lentLog} />
lentLog 로딩 전에 렌더해주는게 없어서 무조건 데이터 없을 때의 내용이 한 번 보입니다.
뷰가 정해진 포맷이라 스켈레톤UI 적용하면 이쁠 거 같은데 일단 저희 메인처럼 로딩 애니메이션 보여주거나 빈 뷰로 보여주는 게 좋을 듯 합니다!
애니메이션 적용한다면 메인처럼 타임아웃 조금 주는게 이쁠거 같네용

2023-01-23 11:09 UTC, 42inshin commented on frontend/src/pages/LogPage.tsx
> +      <LogTable data={lentLog} />
오호 그렇네요?! 좋은 피드백입니다~~ 이것도 확인해서 고치도록하겠습니다 ㅎㅎ

2023-01-23 11:10 UTC, 42inshin commented on frontend/src/App.tsx
> +import React, { Suspense } from "react";
네넵 ㅎㅎ 삭제해서 다시 올리겠습니다

2023-01-23 19:57 UTC, 42inshin commented
이렇게 해도 되는지 모르겠지만,, 
데이터 성공, 실패, 진행 중인 상황에 따라 각각 보여주는 컴포넌트를 다르게 하여 처리했습니다.

2023-01-24 01:43 UTC, Oris482 approved these changes
고생하셨습니다!👍

2023-01-24 05:11 UTC, SeyoungCho commented on frontend/src/components/LentLog/LogTable/LogTable.tsx
> +  lentLog: LentLogDto[] | typeof BAD_REQUEST | undefined;
BAD REQUEST의 type은 어떤건가요??

2023-01-24 05:14 UTC, SeyoungCho approved these changes
끝이 보이는군요 수고많으셨습니다 감사합니다

2023-01-24 05:15 UTC, merged