[FE] FEAT: 검색바 UX 개선 #943
innovationacademy-kr/42cabi pull request #944
Opened 2023-02-07 14:34 UTC by 42inshin

## 해당 사항 (중복 선택)

- [X] FEAT : 새로운 기능 추가 및 개선
- [ ] FIX : 기존 기능 수정 및 정상 동작을 위한 간단한 추가, 수정사항
- [ ] BUG : 버그 수정
- [ ] REFACTOR : 결과의 변경 없이 코드의 구조를 재조정
- [ ] TEST : 테스트 코드 추가
- [ ] DOCS : 코드가 아닌 문서를 수정한 경우
- [ ] REMOVE : 파일을 삭제하는 작업만 수행
- [ ] RENAME : 파일 또는 폴더명을 수정하거나 위치(경로)를 변경
- [ ] ETC : 이외에 다른 경우 - 어떠한 사항인지 작성해주세요.

## 설명
>아래 링크에 이슈번호를 적어주세요. 예) .../42cabi/issues/738

https://github.com/innovationacademy-kr/42cabi/issues/943

- 검색바에서 외 다른 곳 클릭 시 리스트 안보이게 처리
- 키보드 up, down 시 검색 리스트 이동 가능하게 처리

2023-02-08 07:52 UTC, Oris482 reviewed
올려주신 PR 확인했습니다.
debounce를 이용하여 api 요청 횟수를 조절한 점이 굉장히 좋네요!
UX를 고려하여 키보드 동작으로 자동완성 리스트에서 항목을 옮길 수 있고, 외부 클릭으로 리스트를 닫을 수 있게 한 점도 너무 좋습니다.

IntraId로 검색했을 때와 cabinetNum으로 검색했을 때의 출력 컴포넌트가 나눠져 있는 것으로 보이는데요, 막상 코드 상에서는 비슷한 부분이 많은 것 같은데 이거는 가독성 측면에서 나눠두신 걸까요?

2023-02-09 06:59 UTC, SeyoungCho commented on frontend/src/components/Search/SearchItemByNum.tsx
> +  const clickHandler = () => {
함수 작명이 컨벤션에 어긋나는것 같아요! 함수명은 동사로 시작하게 작명하기로 되어 있어서 handleSearchItemOnClick과 같은 이름을 써야할듯 싶습니다..

2023-02-09 07:07 UTC, SeyoungCho commented on frontend/src/components/TopNav/SearchBar/SearchBar.tsx
> +        setTargetIndex((prev) =>
targetIndex라는게 서치 미리보기의 몇 번째인지를 알려주는 상태인가요?

2023-02-09 07:09 UTC, SeyoungCho requested changes
SearchBarList 컴포넌트에 함수명들 대부분 ~handler로 작명하셨던데 컨벤션에 맞게 동사로 시작하게 다시 작명해주시면 될 것 같습니다. useRef활용도가 정말 좋은것 같아요! 확실히 UX가 개선될 것 같습니다 정말 실력이 좋으신것같아요 ㅜㅜㅜ 리액트 처음하시는거 맞으십니까..

2023-02-10 14:59 UTC, 42inshin commented
> 올려주신 PR 확인했습니다. debounce를 이용하여 api 요청 횟수를 조절한 점이 굉장히 좋네요! UX를 고려하여 키보드 동작으로 자동완성 리스트에서 항목을 옮길 수 있고, 외부 클릭으로 리스트를 닫을 수 있게 한 점도 너무 좋습니다.
> 
> IntraId로 검색했을 때와 cabinetNum으로 검색했을 때의 출력 컴포넌트가 나눠져 있는 것으로 보이는데요, 막상 코드 상에서는 비슷한 부분이 많은 것 같은데 이거는 가독성 측면에서 나눠두신 걸까요?

intraId 검색과, cabinetNum으로 검색했을때 기능이 유사하지만, intraId 검색 시의 추가 조건들이 더 있습니다. 검색 된 유저가 빌린 사물함에 없더라도 검색결과에 포함되어 있고, 그때 보여줄 컴포넌트가 다른 모습이라 추가된 기능들이 있습니다. 또한 isSelect(클릭 했을때 사물함 상세정보 나오는 조건)의 조건이 다르기도 합니다.
 이러한 이유로 두개를 합치기 보다는 분리해서 작업을 했는데, 추후에 다시 하나로 합칠 수 있는지 조건 확인해봐서 고려해보도록 하겠습니다.

2023-02-10 15:01 UTC, 42inshin commented on frontend/src/components/TopNav/SearchBar/SearchBar.tsx
> +        setTargetIndex((prev) =>
targetIndex는 검색바에서 검색했을 때 나오는 검색 리스트에서, 키보드 up, down 화살표 사용 시 활성화 되는 list 요소(item)의 index 입니다.

2023-02-10 15:22 UTC, 42inshin commented on frontend/src/components/Search/SearchItemByNum.tsx
> +  const clickHandler = () => {
맞네요~ 작업하다가 컨벤션을 깜빡했습니다. 해당 내용은 바로 수정해서 올리겠습니다

2023-02-11 02:17 UTC, SeyoungCho approved these changes
아주좋습니다!!

2023-02-11 14:09 UTC, Oris482 approved these changes
확인했습니다!
말씀해주신대로 다르게 처리해야되는 부분들이 많으면 지금처럼 파일을 분리해서 작업하는게 좋을 것 같아요! 고생하셨습니다!

2023-02-11 14:20 UTC, oyhoyhk approved these changes
수고 많으셨습니다

커밋이 혼자 하신 작업에서도 10개나 되네요

인신님만큼은 아니더라도 어드민 작업 열심히 하겠습니다

항상 감사합니다!

2023-02-11 14:20 UTC, merged